version: '3'

services:
  gtfsapi:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_URL: 'mysql+pymysql://gtfs:SDsFsiNd_-hzpe_uhCFi@mysql/gtfs'
      PYTHONPATH: '/usr/src/app'
    volumes:
      - ./gtfs/:/usr/src/app/gtfs
    links:
      - mysql
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    command: python /usr/src/app/gtfs_api/app.py

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'QMGg37NBxMn_Drnz6YEE'
      MYSQL_DATABASE: 'gtfs'
      MYSQL_USER: 'gtfs'
      MYSQL_PASSWORD: 'SDsFsiNd_-hzpe_uhCFi'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci